//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldOfGeneticPlants.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class BaseWorld : global::System.Configuration.ApplicationSettingsBase {
        
        private static BaseWorld defaultInstance = ((BaseWorld)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BaseWorld())));
        
        public static BaseWorld Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int WorldHeight {
            get {
                return ((int)(this["WorldHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int WorldWidth {
            get {
                return ((int)(this["WorldWidth"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public uint Plant_Lifelong {
            get {
                return ((uint)(this["Plant_Lifelong"]));
            }
            set {
                this["Plant_Lifelong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int BlockPlant_EnergyNewBlockPlant {
            get {
                return ((int)(this["BlockPlant_EnergyNewBlockPlant"]));
            }
            set {
                this["BlockPlant_EnergyNewBlockPlant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BlockPlant_EnergyConsumptionForTick {
            get {
                return ((int)(this["BlockPlant_EnergyConsumptionForTick"]));
            }
            set {
                this["BlockPlant_EnergyConsumptionForTick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int BlockPlant_EnergyConsumptionForNewBlock {
            get {
                return ((int)(this["BlockPlant_EnergyConsumptionForNewBlock"]));
            }
            set {
                this["BlockPlant_EnergyConsumptionForNewBlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Camera_Zoom {
            get {
                return ((int)(this["Camera_Zoom"]));
            }
            set {
                this["Camera_Zoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int World_SunEnergyBase {
            get {
                return ((int)(this["World_SunEnergyBase"]));
            }
            set {
                this["World_SunEnergyBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int World_SunEnergyModifierForLevel {
            get {
                return ((int)(this["World_SunEnergyModifierForLevel"]));
            }
            set {
                this["World_SunEnergyModifierForLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int World_SunEnergyTakeLevels {
            get {
                return ((int)(this["World_SunEnergyTakeLevels"]));
            }
            set {
                this["World_SunEnergyTakeLevels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int World_Gravitation {
            get {
                return ((int)(this["World_Gravitation"]));
            }
            set {
                this["World_Gravitation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int Genocode_MaxGenes {
            get {
                return ((int)(this["Genocode_MaxGenes"]));
            }
            set {
                this["Genocode_MaxGenes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Genocode_MutationsIndex {
            get {
                return ((int)(this["Genocode_MutationsIndex"]));
            }
            set {
                this["Genocode_MutationsIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Genocode_FrequencyConditionalGene {
            get {
                return ((int)(this["Genocode_FrequencyConditionalGene"]));
            }
            set {
                this["Genocode_FrequencyConditionalGene"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Genocode_PercentageMutations {
            get {
                return ((int)(this["Genocode_PercentageMutations"]));
            }
            set {
                this["Genocode_PercentageMutations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Genocode_MaxChromosome {
            get {
                return ((int)(this["Genocode_MaxChromosome"]));
            }
            set {
                this["Genocode_MaxChromosome"] = value;
            }
        }
    }
}
